### ISSUE TITLE
Cant read the docs

### ISSUE THREAD

**Issue by hanoisteve** [maxnilz/grpc-istio-demo#1]
I would like to read the articles.  Where can I see them? Link does not seem to work.

**Comment by hanoisteve** [comment]
Also I want to see how you would connect a grpc client from outside kubernetes cluster in addition to web-grpc approach.  How would a go client sitting outside the cluster reach all the way through to the service using GRPC end-to-end Thanks

**Comment by maxnilz** [comment]
Hi, I didn't expect the repo might be explored by other guys ever, haha...

Here is the answer to your question(sorry for reply so lately)
> I would like to read the articles. Where can I see them? Link does not seem to work.

There is a  link in `README.md` is work now

> Also I want to see how you would connect a grpc client from outside kubernetes cluster in addition to web-grpc approach. How would a go client sitting outside the cluster reach all the way through to the service using GRPC end-to-end Thanks

I'm using `minikube` for this demo,  and you can find there is a makefile in the repo in which you can find a target can be performed by using  `make run-client-istio-grpc-raw` 

BTW: before you perform `make run-client-istio-grpc-raw` you might need to export `GATEWAY_URL` for you istio-ingressgateway IP address(if you are using minikube as well)

how you can get the istio-ingressgatway IP address?
```
kubectl get svc  -o wide -n istio-system | grep ingressgateway
```
If your cluster is running in an environment that does not support an external load balancer (e.g., minikube), the EXTERNAL-IP of istio-ingressgateway will say `<pending>`. To access the gateway, use the service’s NodePort, or use port-forwarding instead.

In my minikube case: 
the EXTERNAL-IP of istio-ingressgateway is <pending> so I get  the `GATEWAY_URL` by `export GATEWAY_URL=$(minikube ip)`
```
 $ kubectl get svc  -o wide -n istio-system | grep ingressgateway
custom-gateway           LoadBalancer   10.107.168.66    <pending>     80:31284/TCP,443:31385/TCP,31400:31013/TCP,15011:31521/TCP,8060:32332/TCP,15029:30062/TCP,15030:32471/TCP,15031:30832/TCP,15032:32682/TCP    34d   app=istio-custom-ingressgateway,istio=custom-ingressgateway,release=istio
istio-ingressgateway     LoadBalancer   10.107.148.204   <pending>     15020:30396/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:30902/TCP,15030:31813/TCP,15031:30194/TCP,15032:32088/TCP,15443:32209/TCP   54d   app=istio-ingressgateway,istio=ingressgateway,release=istio
```

Hope this will be helpful
